In [11]:
import numpy as np

In [3]:
with open("input/09", "r") as fp:
    txt = fp.read()[:-1]

In [5]:
my_txt = txt

lines = my_txt.split("\n")

In [7]:
def process_line(line):
    return list(map(int, line.split()))

# Part 1

In [27]:
def analysis(XX, verbose=True):
    mem = [XX[-1]]
    
    while True:
        XX = np.diff(XX)
        mem.append(XX[-1])
        if verbose:
            print(XX)
        
        if len(set(XX)) == 1:
            break
    
    return mem

In [28]:
def reconstruct(mem):
    v = 0
    for vi in mem[::-1]:
        v = vi + v
    
    return v

In [33]:
tot = 0
for line in lines:
    vals = process_line(line)
    mem = analysis(vals, verbose=False)
    res = reconstruct(mem)
    tot += res
    
print("Part 1: {}".format(tot))

Part 1: 1798691765


# Part 2

In [34]:
def analysis_left(XX, verbose=True):
    mem = [XX[0]]
    
    while True:
        XX = np.diff(XX)
        mem.append(XX[0])
        if verbose:
            print(XX)
        
        if len(set(XX)) == 1:
            break
    
    return mem

In [35]:
def reconstruct_left(mem):
    v = 0
    for vi in mem[::-1]:
        v = vi - v
    
    return v

In [36]:
example = "10  13  16  21  30  45"
vals = process_line(example)
mem = analysis_left(vals)
reconstruct_left(mem)

[ 3  3  5  9 15]
[0 2 4 6]
[2 2 2]


5

In [38]:
tot = 0
for line in lines:
    vals = process_line(line)
    mem = analysis_left(vals, verbose=False)
    res = reconstruct_left(mem)
    tot += res
    
print("Part 2: {}".format(tot))

Part 2: 1104
